version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: stiljira_app
    ports:
      - '3000:3000'
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
    depends_on:
      - stiljira_db

  stiljira_db:
    container_name: stiljira_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
